about:
  - "**Team player with positive attitude** who has experience working both remotely and in-person in an Agile environment using Scrum methodologies. Fan of peer reviews. Worked together with product management, DevOps, and UI/UX designers. Have been part of both a small start-up team and a large multi-squad project."
  - "**Highly motivated software developer** with 4+ years of work experience in web development and data science. Worked both on front-end and back-end. Proficient in TypeScript, CSS, React, Python, and Haskell while having solid understanding of many other languages. Skilled in building beautiful UIs and writing elegant, readable, and maintainable code."
  - "**Love taking on challenges, learning new things, and enjoy problem solving at its core.** Highly receptive to feedback with a strong drive for self-improvement and mastering the art of software engineering."
  - "To this day proud of my bachelor’s thesis on [Game Development in Haskell](https://github.com/honzaflash/ba-thesis) which early on shows my **curiosity, willingness to challenge myself, and my ability to understand and analyze high level concepts.**"

interests:
  - Ultimate Frisbee player, ex-coach, and team co-founder
  - Led a church youth club for a few years
  - Maker, designer, techie, 3D printer, and beginner woodworker
  - Car enthusiast and DIY mechanic
  - PC gamer and board gamer
  - Drummer
  - Hiker
