Masaryk University:
  from: Sep 2018
  to: Jun 2021
  subtitle: Bachelor's degree in Computer Sciences
  website: https://www.fi.muni.cz/
  description:
    - The final thesis [Game Development in Haskell](https://github.com/honzaflash/ba-thesis) shows my curiosity, willingness to challenge myself, and my ability to understand and analyze high level concepts early on. In a single semester, researched available frameworks, learned different approaches to game engine design, implemented two versions of a game, and wrote an extensive analysis and a summary of my experience. The thesis received an A

  courses:
    - Software Engineering I
    - Algorithms and Data Structures I
    - Computability and Complexity
    - Automata and Grammars
    - Database Systems: [be]
    - Computer Network Services
    - Seminar on Functional Programming
    - Java: [be]
    - C++ programming: [be]
    - Principles of Low-Level Programming: [be]
    - Generative Design Programming: [fe]
    - Game Design I: [game]

Hyperskill.org/JetBrains Academy:
  to: May 2022
  subtitle: Kotlin Core Course
  description:
    - Gained solid understanding of Kotlin through quizzes, a practice project, and reading through the language documentation 
    - Refreshed knowledge of Object Oriented principles
    - Followed up by learning the basics of microservice architecture and Spring Boot 
  relevancy: [be]
