hard:
  advanced:
    JavaScript: [fe, be]
    TypeScript: [fe, be, chain]
    Haskell: [fe, be, chain]
    React: [fe]
  intermediate:
    C++: [be]
    Python: [be]
    Graphic Design: [fe, web]
    Node.js: [be]
    HTML: [fe]
    CSS: [fe]
    Redux Toolkit: [fe]
    Material UI: [fe]
    Express.js: [be]
    REST APIs: [fe, be]
    PostgreSQL: [be]
    Git: [all]
    Jira/Atlassian: [all]
  familiar:
    Jest.js: [fe]
    jQuery: [fe]
    Kotlin: [be, chain]
    Java: [be]
    Rust: [be, chain]
    Go: [be, chain]
    Kafka: [be]
    CI/CD: [fe, be]
    Mircoservices: [be]
    Spring Boot: [be]

soft: [Love of learning, Problem solving, Attention to detail, Teamwork, Code ownership, Agile]
