hard:
  advanced:
    JavaScript: any
    TypeScript: any
    Functional React Components: [func]
    Haskell: any
    React: [fe, fs, all]
  intermediate:
    C/C++: [be, fs, all]
    Python: [be, fs, data, all]
    Graphic Design: [fe, web, all]
    lodash: [func]
    Haddock: [func]
    Haskell Stack tool: [func]
    Node.js: [be, fs, data, chain, all]
    HTML: [fe, web, fs, all]
    CSS: [fe, web, fs, all]
    Redux Toolkit: [fe, fs, all]
    Material UI: [fe, fs, all]
    Express.js: [be,fs, all]
    REST APIs: [fe, be, fs, all]
    PostgreSQL: [be, fs, all]
    Git: any
    Jira/Atlassian: any
  familiar:
    Jest.js: [fe, fs, all]
    jQuery: [fe, all]
    NumPy: [data]
    Pandas: [data]
    Kotlin: [be, fs, chain, func, all]
    Java: [be, fs, all]
    Rust: [be, fs, chain, func, all]
    Go: [be, fs, chain, all]
    Kafka: [be, fs, all]
    CI/CD: any
    Mircoservices: [be, fs, chain, all]
    Spring Boot: [be, fs, all]

soft: [Love of learning, Problem solving, Attention to detail, Teamwork, Code ownership, Agile]
