Vacuumlabs:
  title: Software Engineer
  companyLink: https://vacuumlabs.com/about/
  from: Jan 2022
  to: Dec 2022
  description:
    - "Worked on two projects: covid-testing laboratory system (full stack) and a [neo bank web app](https://vacuumlabs.com/case-study/advance-intelligence/) (front end)"
    - Was promoted to a higher level both times my performance was evaluated because of my receptivity to criticism
    - Suggested automating TypeScript type generation for our APIs and created the script for it. That made our app more type-safe, saved us time and made it easy to keep updating the types as the backend changed
    - Helped with upholding high standard by pushing for clear, expressive, and type-safe code through suggestions in reviews and discussions: [^func]
    - Pushed for clear, expressive, and type-safe code in functional style through suggestions in reviews and discussions improving our code quality: [func]
    - Took part in defining code-style and shared my knowledge of making a good use of TypeScript: [fe, fs, func, all]
    - Built main account, saving accounts, and loan views with one common React component minimizing duplicate code while using type templates, and narrowing to keep everything clear and type-safe: [fe, fs, all]
    - Understood design requirements and resolved few misunderstandings before a wrong feature was implemented
    - Was trusted to write extra documentation to ensure smooth project handover
    - Helped to refactor database relationships and wrote SQL database migrations when expanding the lab system to ensure better scalability and preserving all current production data. This allowed us to pivot to other kinds of testing in addition to covid-tests: [be, fs, all]
    - Became very interested in block-chain technology during that time as Vacuumlabs worked on many 'crypto' projects: [chain]

Masaryk University:
  title: Web Developer and Designer
  from: Feb 2020
  to: Dec 2022
  description:
    - Collaborated remotely with university teachers to create non-linear interactive stories for educational purposes
    - Exceeded expectations by providing beautiful visuals suiting each story’s theme and extra functionality
    - Used creative problem solving and web design skills (JS, HTML, CSS) to fulfill requirements and creative vision despite technical limitations of the tool used for creating the games: [^fe, ^web]
    - Used creative problem solving, web design (JS, HTML, CSS), and graphic design skills to fulfill requirements and creative vision despite technical limitations of the tool used for creating the games: [fe, web]
    - Created a custom tool that made developer experience much better
